public enum MeasurementUnits {
    FEET, FEET_TO_INCH, INCH, INCH_TO_FEET,
    FEET_TO_YARD, YARD_TO_FEET, YARD,
    INCH_TO_YARD, YARD_TO_INCH,
    INCH_TO_CM, CM_TO_INCH,
    GALLON_TO_LITRES, LITRES_TO_GALLON, GALLON,
    LITER_TO_MILLILITER, MILLILITER_TO_LITER, LITER,
    KG_TO_GRAMS, TONNE_TO_KG, GRAM_TO_KG,
    KG_TO_TONNE, FAHRENHEIT_TO_CELSIUS, CELSIUS_TO_FAHRENHEIT;
}
